#!/bin/bash

build_stats () {
  echo -n '{ "build_timestamp" : "'
  date "+%Y-%m-%d %H:%M:%S" | tr -d '\n'

  echo -n '", "git_revision" : "'
  git rev-parse HEAD | tr -d '\n'

  echo -n '", "version" : "'
  git tag -l \
    | grep release \
    | tr '-' ' ' \
    | awk '{ print $2 }' \
    | sort -V \
    | tail -n 1 \
    | tr -d '\n'

  echo '"}'
}

function cleanup {
  rm BUILD_DETAILS
}
trap cleanup EXIT

build_stats > BUILD_DETAILS

# The `buildx` and `--platform` flags allows images built on M1 mac to be
# pushed to arm64 runners (e.g. aws ecs fargate).
docker buildx build . \
  --platform linux/amd64,linux/arm64 \
  -t my_lucky_app \
  --progress plain
