require "./shards"

# Load the asset manifest
Lucky::AssetHelpers.load_manifest "public/mix-manifest.json"

require "../config/server"
require "../config/**"
require "./app_database"
require "./models/base_model"
require "./models/mixins/**"
require "./models/**"

require "./jobs/**"
require "./queries/mixins/**"
require "./queries/**"
require "./operations/mixins/**"
require "./operations/**"
require "./serializers/base_serializer"
require "./serializers/**"
require "./emails/base_email"
require "./emails/**"
require "./actions/mixins/**"
require "./actions/**"
require "./components/base_component"
require "./components/**"
require "./policies/application_policy"
require "./policies/**"
require "./pages/base_layout"
require "./pages/**"
require "../db/migrations/**"
require "./app_server"
